on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: azure/docker-login@v1
      with:
        login-server: mykuberegplay.azurecr.io
        username: ${{ secrets.acr_mykuberegplay_username }}
        password: ${{ secrets.acr_mykuberegplay_password }}
    
    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/AdventureWorks" -f  "AdventureWorks" -t mykuberegplay.azurecr.io/mykubernetesdev:${{ github.sha }} --label dockerfile-path=AdventureWorks
        docker push mykuberegplay.azurecr.io/mykubernetesdev:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: ${{ secrets.aks_mykubernetesdev_kubeConfig }}
      id: login
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep mykubernetesdevadventureworks | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace mykubernetesdevadventureworks`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: mykubernetesdevadventureworks
        container-registry-url: mykuberegplay.azurecr.io
        container-registry-username: ${{ secrets.acr_mykuberegplay_username }}
        container-registry-password: ${{ secrets.acr_mykuberegplay_password }}
        secret-name: mykubernetesdockerauth
       
    - uses: azure/k8s-deploy@v1.2
      with:
        namespace: mykubernetesdevadventureworks
        manifests: |
          manifests/deployment.yml
          manifests/service.yml
        images: |
          mykuberegplay.azurecr.io/mykubernetesdev:${{ github.sha }}
        imagepullsecrets: |
          mykubernetesdockerauth
